[package]
name = "onesec_forwarder_lambda_core"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
itertools.workspace = true
onesec_forwarder_types.path = "../../types"
tracing.workspace = true
